### ISSUE TITLE
Need a search dialog

### ISSUE THREAD

**Issue by matt454357** [brenkmanco/hackpdm#5]
Make a dialog that accepts various search criteria, and returns a list of matching entries from the database.

Search:
- textbox: filename
- checkbox: checked out to me
- file properties
  - selectbox: property name
  - checkbox: not
  - selectbox: operator
  - textbox: value

**Comment by briggsj3** [comment]
Search dialog now has following functionality:
 -Hit enter to search
 -Case insensitive searches (part name and textual properties)
 -Search by property (text, number, date, and boolean types allowed (but not fully tested))
 -Searching text_value type properties uses a "LIKE '%X%'" query
 -Leaving "Property Contains" text field empty with a Property selected in the drop-down menu will search using "NOT NULL" SQL query
 -Property drop-down gives autosuggestions
 -Checking the "Checked Out to Me" box returns only files belonging to you
 -If a property field is used (via the Property drop-down), then a third column appears in the search results with the value for that selected property in each returned file
 -Double-clicking on a returned filename will close the dialog and navigate to that file in the Main Window (expanding the parent directories and highlighting the file appropriately)

TODO:
 -Implement "Deleted Existing Locally" and "Only Existing Locally" checkboxes (a utility function was created that recursively discovers all files in a directory).

**Comment by briggsj3** [comment]
Added "Deleted Existing Locally" functionality.

TODO:  Implement "Only Existing Locally" -> Would this and "Deleted Existing Locally" be mutually exclusive (i.e., if both boxes are checked, which should take precedence?)?

**Comment by matt454357** [comment]
It has been implemented as mutually exclusive for now.  I can't think of a reason to do it any other way.

**Comment by matt454357** [comment]
@briggsj3 pushed commit 30b82ef:

> Added support for searching for files that exist only locally.  Currently allows searching by filename (using sql LIKE command), or if "Filename Contains" entry is blank, then returns all local-only files. Does not currently allow searching by property.
> 
> TODO:  Allow searching local-only files by property (necessary?).

The core functionality has been implemented.  I'm going to close this issue, and start some new issues for a few lingering bugs.
