### ISSUE TITLE
Searching Checked Out to Me fails

### ISSUE THREAD

**Issue by matt454357** [brenkmanco/hackpdm#9]
Receiving an error message when search for all files "Checked Out to Me".

> Search Error:
> No search parameters provided.  Search not performed.

![checked_out_to_me_failed](https://cloud.githubusercontent.com/assets/7604932/7712132/88052442-fe2c-11e4-9105-b67eff6d994b.jpg)

**Comment by briggsj3** [comment]
This is resolved with commit a131958.
